### ISSUE TITLE
How to use a client certificate (crt) with oAuthSwift on iOS ?

### ISSUE THREAD

**Issue by fvvliet** [OAuthSwift/OAuthSwift#444]
### OAuth Version:
- [ ] Version 1
- [ x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [ x] CocoaPods
- [ ] Manually

### Library version:
- [ ] head
- [ ] v1.2 (Swift 4.0)
- [ ] v1.0.0
- [ ] v0.6
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x ] 9.0 (Swift 4.0)
- [ ] 9.0 (Swift 3.2)
- [ ] 8.x (Swift 3.x)
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

I have to include a client certificate (.crt) to communicate with the oAuth server of a customer. Is this possible with oAuthSwift framework ? Can anyone point me to an explanation / example code how to do this ?

Thanks for your advice
Frank

**Comment by phimage** [comment]
OAuthSwift use standard network layer and default URLSessionConfiguration
see URLSessionFactory code

what you want to achieve is ssl pinning
https://infinum.co/the-capsized-eight/how-to-make-your-ios-apps-more-secure-with-ssl-pinning

OAuthSwift is not the place to discuss about that
Feel free to open issue if there is some problem to do it specifically with OAuthSwift due to framework implementation

**Comment by fvvliet** [comment]
Thank you for the link !!
Frank
