### ISSUE TITLE
SFAuthenticationURLHandler and ASWebAuthenticationURLHandler are internal?

### ISSUE THREAD

**Issue by sprynmr** [OAuthSwift/OAuthSwift#557]
### Description:

Curious why the two more "modern" handlers are not available without subclassing them?

### OAuth Version:
- [ ] Version 1
- [x] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ ] v2.1.0
- [x] v2.0.0
- [ ] v1.4.1
- [ ] v1.2 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [ ] 10.x (Swift 4.1)
- [ ] 9.3 (Swift 4.1)
- [ ] 9.0 (Swift 4.0)
- [ ] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by sprynmr** [comment]
nvm, user error.

**Comment by jonchui** [comment]
I must be hitting the same user error, b/c I'd to know the same thing? 

I tried to use `SFAuthenticationURLHandler` by a basic subclass:

```
class GlooAuthURLHandler : SFAuthenticationURLHandler {
    
    override init(callbackUrlScheme: String) {
        super.init(callbackUrlScheme:callbackUrlScheme)
    }
}
```

But get the error:
`'SFAuthenticationURLHandler' initializer is inaccessible due to 'internal' protection level`

Removing the call to `super.init` results in the error:

`'GlooAuthURLHandler' cannot be constructed because it has no accessible initializers`

**Comment by sprynmr** [comment]
I believe I was using an older version. Try v 2.1.0
