### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".'

### ISSUE THREAD

**Issue by khsalman** [OAuthSwift/OAuthSwift#676]
### Description:
I am continuously receiving this "Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".'" error on iOS 14.5+ devices. Below iOS 14.5 everything was working perfect.  It says I cannot make any callback url with using : and // But Fitbit's panel does not allow me to have a callback url without using ://
Please anyone can suggest me any solution?
### OAuth Version:
- [ ] Version 1
- [ ] Version 2

### OS (Please fill the version) :
- [x] iOS :
- [ ] OSX :
- [ ] TVOS :
- [ ] WatchOS  :

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually

### Library version:
- [ ] head
- [ ] v2.1.0
- [ ] v2.0.0
- [ ] v1.4.1
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 11.4 (Swift 5.2)
- [ ] 11.x (Swift 5.1)
- [ ] 10.x (Swift 5.0)
- [x] other: (Please fill in the version you are using.)

- [ ] objective c

**Comment by phatblat** [comment]
My team ran into this issue as well. It's a change to the Apple [`ASWebAuthenticationSession`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) behavior of the `callbackURLScheme` parameter; it should be a _scheme_ and **NOT** a full URL. If you pass a full URL (containing a `:`) it will be emit a console warning about the invalid scheme on iOS 14.4 and lower, but it is a runtime exception on iOS 14.5+.

This OAuthSwift library did not change this behavior but before #654 you actually couldn't get OAuth errors returned  unless you _did_ pass a URL in the `callbackURLScheme` parameter. This was fixed in 2.2.

I would describe this as "expected behavior" now. Change your code to pass in only your app's [custom scheme](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app) (not the full URL) in the `callbackURLScheme` parameter.
